# SPDX-FileCopyrightText: Copyright (c) 2026 Cooper Dalrymple (@relic-se)
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
